---

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - lsb-release

- name: Add repo key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add apt repo for node
  apt_repository:
    repo: deb https://deb.nodesource.com/node_10.x stretch main

- name: Install nodejs package
  apt:
    name: nodejs
