---

- include: install_older_nodejs.yml
  when: ansible_distribution_release == 'stretch' or ansible_distribution_release == 'jessie'

- name: Install needed packages
  apt:
    name: "{{ wizzy_npm_package }}"
    state: present
  when: ansible_distribution_release != 'stretch' and ansible_distribution_release != 'jessie'

- name: Create wizzy working directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /usr/local/share/wizzy
    - /usr/local/share/wizzy/conf

- name: Install wizzy package
  npm:
    name: wizzy
    global: yes
    path: /usr/local/share/wizzy

- name: Create wizzy config file
  template:
    src: wizzy.json.j2
    dest: /usr/local/share/wizzy/conf/wizzy.json
